# Generated by Django 5.2 on 2025-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20210708_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.CharField(choices=[('Patna', 'Patna'), ('Ranchi', 'Ranchi'), ('Dhanbad', 'Dhanbad'), ('Gaya', 'Gaya'), ('Other', 'Other')], default='Patna', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_owner_phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
